---
 - name: Checks for uncommitted changes and commits if necessary.
   hosts: '{{ target | default("palo_devices") }}'
   connection: local

   vars_prompt:
      - name: username
        prompt: Palo Username
        private: no

      - name: password
        prompt: Palo Password
        private: yes

      - name: api_key
        prompt: Palo API Key
        private: yes

   vars:
      device:
        ip_address: 192.168.99.15
        api_key: '{{ api_key }}'

   tasks:
     - name: Check for pending changes
       paloaltonetworks.panos.panos_op:
         provider: '{{ device }}'
         cmd: 'show config list changes'
       register: changes

     - name: Display changes
       ansible.builtin.debug:
         msg: '{{ changes.stdout | from_json }}'
 
     - name: Commit changes if needed
       paloaltonetworks.panos.panos_commit_firewall:
         provider: '{{ device }}'
       when: >
         (changes.stdout | from_json).response.result.journal is defined and
         (changes.stdout | from_json).response.result.journal.entry | length > 0

