---
- name: Update FreeRadius certificate
  gather_facts: false
  hosts: localhost

  tasks:
    - name: Create certificate signing request (CSR) for self-signed certificate
      community.crypto.openssl_csr_pipe:
        privatekey_path: radius.domain.org.key
        common_name: Generic Domain Certificate Authority
        organizationName: Generic Domain, LLC.
        privatekey_passphrase: passphrase
      register: csr
      become: true
      become_user: root

    - name: Renew self-signed certificate from CSR
      community.crypto.x509_certificate:
        path: radius.domain.org.crt
        csr_content: "{{ csr.csr }}"
        privatekey_path: radius.domain.org.key
        privatekey_passphrase: passphrase
        provider: selfsigned
        selfsigned_not_after: +365d # valid for one year
        selfsigned_not_before: "-1d" # valid since yesterday
        selfsigned_digest: "sha256" # this is the default and can be omitted
      become: true
      become_user: root

- name: Backup existing keys, certificates, copy new keys, certificates and restart Free Radius
  hosts: freeradius

  tasks:
  - name: Backup radius.domain.org.key
    ansible.builtin.copy:
      src: /etc/raddb/certs/radius.domain.org.key
      dest: /etc/raddb/certs/radius.domain.org.key.backup
      remote_src: yes
    become: true
    become_user: root

  - name: Backup radius.domain.org.crt Certificate
    ansible.builtin.copy:
      src: /etc/raddb/certs/radius.domain.org.crt
      dest: /etc/raddb/certs/radius.domain.org.crt.backup
      remote_src: yes
    become: true
    become_user: root

  - name: Copy new radius.domain.org.key to remote servers
    ansible.builtin.copy:
      src: radius.domain.org.key
      dest: /etc/raddb/certs/radius.domain.org.key
      remote_src: no
    become: true
    become_user: root

  - name: Copy new radius.domain.org.crt certificate to remote servers
    ansible.builtin.copy:
      src: radius.domain.org.crt
      dest: /etc/raddb/certs/radius.domain.org.crt
      remote_src: no
    become: true
    become_user: root

  - name: restart freeradius
    ansible.builtin.systemd_service:
      name: radiusd.service
      state: restarted
    become: yes
    become_user: root
