---
 - name: Perform a Junos OS software upgrade
   hosts: juniper
   connection: local
   gather_facts: no

   vars_prompt:
      - name: username
        prompt: Junos Username
        private: no

      - name: password
        prompt: Junos Password
        private: yes

   tasks:
     - name: Upgrade Junos OS
       juniper.device.software:
         local_package: "junos-srxsme-24.2R1.17.tgz"
         no_copy: false
         validate: True
       register: response

     - name: Print the response
       debug:
         var: response
