---
 - name: Apply Basic ADC Config to A10 
   hosts: a10_vthunder
   connection: local
   gather_facts: false

   vars_prompt:
      - name: username
        prompt: A10 Username
        private: no

      - name: password
        prompt: A10 Password
        private: yes

   tasks:

      - name: Configure NAT pool
        a10.acos_axapi.a10_ip_nat_pool:
          ansible_username: '{{ username }}'
          ansible_password: '{{ password }}'
          ansible_host: "{{ ansible_host }}"
          ansible_port: "{{ ansible_port }}"
          state: present
          pool_name: natpool
          start_address: 10.10.15.111
          end_address: 10.10.15.111
          netmask: 255.255.255.0

      - name: Configure Health Monitor
        a10.acos_axapi.a10_health_monitor:
          ansible_username: '{{ username }}'
          ansible_password: '{{ password }}'
          ansible_host: "{{ ansible_host }}"
          ansible_port: "{{ ansible_port }}"
          state: present
          up_retry: 1
          retry: 3
          timeout: 5
          interval: 5
          method:
            tcp:
              method_tcp: 1
              tcp_port: 80
          name: health_monitor1

      - name: Configure Servers and Service Group
        a10.acos_axapi.a10_slb_service_group:
          ansible_username: '{{ username }}'
          ansible_password: '{{ password }}'
          ansible_host: "{{ ansible_host }}"
          ansible_port: "{{ ansible_port }}"
          protocol: tcp
          health_check: health_monitor1
          member_list:
            - host: 10.10.15.1
              name: server-1
              port: 80
            - host: 10.10.15.2
              name: server-2
              port: 80
          lb_method: dst-ip-hash
          name: Ansible-servicegroup

      - name: Configure Virtual Server
        a10.acos_axapi.a10_slb_virtual_server:
          ansible_username: '{{ username }}'
          ansible_password: '{{ password }}'
          ansible_host: "{{ ansible_host }}"
          ansible_port: "{{ ansible_port }}"
          state: present
          name: VIP-TCP
          ip_address: 10.11.0.1
          netmask: 255.255.255.0
          enable_disable_action: enable
          stats_data_action: stats-data-enable
          port_list:
            - name: vport_ansible_demo
              protocol: tcp
              port_number: 80
              action: enable
              pool: natpool
              service_group: Ansible-servicegroup
