---
 - name: Configure top level config
   hosts: nexus9k
   gather_facts: false

   tasks:
     - name: Configure hostname
       cisco.ios.ios_hostname:
        config:
          hostname: "{{ inventory_hostname }}"
        state: merged

     - name: configure name servers
       cisco.ios.ios_system:
         name_servers:
         - 192.168.120.1

     - name: Update login banner
       nxos_banner:
         banner: motd
         text: "{{ lookup('file', './raw_banner.cfg') }}"
         state: present
