--- 
 - name: Get Junos OS configuration via SSH
   hosts: juniper
   connection: local
   gather_facts: no
   roles:
     - juniper.junos

   tasks:

     - name: Get selected configuration hierarchies
       juniper.device.config:
         retrieve: "committed"
         filter: "interfaces"
         format: "xml"
       register: response

     - name: "Print result"
       debug:
         var: response
